FROM python

RUN mkdir /home/murali
WORKDIR /home/murali

RUN apt-get update
RUN apt-get install -y libnss3 libgconf-2-4 libgtk-3-0 libx11-xcb1 libxkbcommon0 libxcb1 libxcomposite1 libxdamage1 libxtst6 libgbm1 libasound2

RUN wget -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/linux64/chrome-linux64.zip --no-check-certificate
RUN unzip chrome-linux64.zip 
RUN chmod +x /home/murali/chrome-linux64/chrome
ENV PATH=$PATH:/home/murali/chrome-linux64

RUN wget -O chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/linux64/chromedriver-linux64.zip --no-check-certificate
RUN unzip chromedriver-linux64.zip 
RUN chmod +x /home/murali/chromedriver-linux64/chromedriver
ENV PATH=$PATH:/home/murali/chromedriver-linux64

RUN mkdir /home/murali/E2E_testing
WORKDIR /home/murali/E2E_testing

COPY . .

RUN pip install --no-cache-dir -r requirements.txt


